name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  NODE_VERSION: 12.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node_modules
      uses: actions/cache@v2.1.4
      id: cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-npm-node${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.OS }}-npm-node${{ env.NODE_VERSION }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile
    - name: Check yarn.lock integrity
      run: yarn check --integrity

    - name: Generator - Typechecking
      run: yarn workspace generator typecheck

    - name: Generator - Linting
      run: yarn workspace generator lint

    - name: Generator - Testing
      run: yarn workspace generator test
